### PR TITLE
Support AU 2024.6.18

### PR DESCRIPTION
**Pull request by IdeaAmongUsTaker**
**Hi I was working on the project i just finished at 00:25pm lmao anyways i upgraded the mod to 2024.6.18 i didn't test i'm busy so i hope this will gonna be merged !!**

### CODE REVIEW

**Comment by IdeaAmongUsTaker** [comment]
@LezaiYa @Rabek009

**Comment by Rabek009** [comment]
I already made support for 2024.6.18 and added few more things. I really appreciate your work, but I already did most of the things. I always made commit before update, because no one ever made pull request. From now I will be making commits more frequently. I can add few things from your commits that I haven't already added.

**Comment by IdeaAmongUsTaker** [comment]
> I already made support for 2024.6.18 and added few more things. I really appreciate your work, but I already did most of the things. I always made commit before update, because no one ever made pull request. From now I will be making commits more frequently. I can add few things from your commits that I haven't already added.

ok so everything you did in your work for 2024.6.18 push it to this pr

**Comment by IdeaAmongUsTaker** [comment]
i'm so excited to be a developer for this mod

**Comment by Rabek009** [comment]
Done!

**Comment by Rabek009** [comment]
Join MGM discord server for easier communication.

**Pull request closed without merging**
